In [1]:
import numpy as np
import pandas as pd

In [3]:
train = pd.read_csv("C:/Users/YHJ/Desktop/Data 교육/수업자료/MachineLearning/titanic_train.csv")
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

# 데이터 셋 : 타이타닉 데이터셋

# 1. 전처리 : train / validation세트 나누기

1. 먼저 feature와 label을 정의
2. feature/label정의 했으면 적절한 비율로  train과 validation을 나눔

In [4]:
feature=['Pclass','Sex','Age','Fare']
label=['Survived']

In [5]:
train[feature].head()

Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [7]:
train[label].head() #survived : 1=생존, 0=사망

Survived
0         0
1         1
2         1
3         1
4         0

In [8]:
from sklearn.model_selection import train_test_split
#파라미터 값


In [13]:
x_train, x_vaild, y_train, y_vaild = train_test_split(train[feature],train[label],
                                                      test_size=0.2,shuffle=True,
                                                      random_state=30)

# 리턴받는 데이터 순서(=split뒤에 파라미터 순서)가 중요함

In [16]:
x_train.shape, y_train.shape

((712, 4), (712, 1))

In [17]:
x_vaild.shape, y_vaild.shape

((179, 4), (179, 1))

# 전처리: 결측치

In [19]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


- **pandas의 isnull()** : 결측치를 확인하는 방법
- sum()을 통해 한눈에 확인 가능

In [20]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

- 개별 column의 결측치에 대해 확인하는 방법

In [22]:
train['Age'].isnull().sum()

177

# (1) Numerical Column(수치형)데이터에 대한 결측치 처리

- fillna(채울 값)
- fillna(열이름.채울값)

In [26]:
train['Age'].fillna(0).describe()

count    891.000000
mean      23.799293
std       17.596074
min        0.000000
25%        6.000000
50%       24.000000
75%       35.000000
max       80.000000
Name: Age, dtype: float64

In [27]:
train['Age'].fillna(train['Age'].mean()).describe()

count    891.000000
mean      29.699118
std       13.002015
min        0.420000
25%       22.000000
50%       29.699118
75%       35.000000
max       80.000000
Name: Age, dtype: float64

## **imputer** : 2개 이상의 column을 한번에 처리할 때

**simplelmputer** : 여러개의 컬럼을 한번에 처리하는 메소드(결측치가 여러개 있을 경우 한번에 처리 가능) 

In [30]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')

## fit : 결측치에 대한 학습 진행

In [31]:
imputer.fit(train[['Age','Pclass']])

SimpleImputer()

## transform() : 실제 결측치에 대한 처리해주는 함수

In [34]:
result = imputer.transform(train[['Age','Pclass']])
result

array([[22.        ,  3.        ],
       [38.        ,  1.        ],
       [26.        ,  3.        ],
       ...,
       [29.69911765,  3.        ],
       [26.        ,  1.        ],
       [32.        ,  3.        ]])

In [35]:
train[['Age','Pclass']] = result
train[['Age','Pclass']].isnull().sum()

Age       0
Pclass    0
dtype: int64

In [36]:
train[['Age','Pclass']].describe()

Age      Pclass
count  891.000000  891.000000
mean    29.699118    2.308642
std     13.002015    0.836071
min      0.420000    1.000000
25%     22.000000    2.000000
50%     29.699118    3.000000
75%     35.000000    3.000000
max     80.000000    3.000000

## fit_transform() : fit()과 transform()을 한번에 해주는 함수

In [40]:
train = pd.read_csv("C:/Users/YHJ/Desktop/Data 교육/수업자료/MachineLearning/titanic_train.csv")
train[['Age','Pclass']].isnull().sum()

Age       177
Pclass      0
dtype: int64

In [43]:
imputer = SimpleImputer(strategy='median')
result = imputer.fit_transform(train[['Age','Pclass']])
train[['Age','Pclass']] = result

In [44]:
train[['Age','Pclass']].isnull().sum()

Age       0
Pclass    0
dtype: int64

In [45]:
train[['Age','Pclass']].describe()

Age      Pclass
count  891.000000  891.000000
mean    29.361582    2.308642
std     13.019697    0.836071
min      0.420000    1.000000
25%     22.000000    2.000000
50%     28.000000    3.000000
75%     35.000000    3.000000
max     80.000000    3.000000

# (2) Categorical(카테고리별) Column 데이터에 대한 결측치 처리

In [ ]:
train = pd.read_csv("C:/Users/YHJ/Desktop/Data 교육/수업자료/MachineLearning/titanic_train.csv")

### 1개의 column을 처리하는 경우

In [47]:
train['Embarked'].fillna('S')

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

### Imputer: 2개 이상의 column을 처리하는 경우

In [50]:
imputer = SimpleImputer(strategy='most_frequent') #최빈값(most_frequent)을 사용하는 전략사용
result = imputer.fit_transform(train[['Embarked', 'Cabin']])
train[['Embarked', 'Cabin']]=result
train[['Embarked', 'Cabin']].isnull().sum()

Embarked    0
Cabin       0
dtype: int64

# (3) Label Encoding

- 문자(categorical)를 수치(numerical)로 변환
- 학습을 위해서 모든 문자로된 **데이터 수치로 변환**하여야 함
- one-hot인코딩보다 label 인코딩이 속도가 더 빠름 (필요에 따라 맞춰 사용)

In [51]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    float64
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object 
 11  Embarked     891 non-null    object 
dtypes: float64(3), int64(4), object(5)
memory usage: 83.7+ KB


In [52]:
def convert(data):
    if data == 'male':
        return 1
    elif data == 'female':
        return 0

In [53]:
train['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [54]:
train['Sex'].apply(convert)

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: int64

In [55]:
from sklearn.preprocessing import LabelEncoder

In [56]:
le = LabelEncoder()

In [57]:
train['Sex_num'] = le.fit_transform(train['Sex'])
train['Sex_num'].value_counts()

1    577
0    314
Name: Sex_num, dtype: int64

In [58]:
le.classes_

array(['female', 'male'], dtype=object)

In [62]:
# nverse_transform : 다시 인코딩한 값을 보여줌
le.inverse_transform([0,1,1,0,0,1,1])

array(['female', 'male', 'male', 'female', 'female', 'male', 'male'],
      dtype=object)

★ 주의) NaN값이 포함되어 있으면, LabelEncoder이 정상작동하지 않음

In [63]:
le.fit_transform(train['Embarked'])

array([2, 0, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2,
       1, 2, 2, 2, 0, 2, 1, 2, 0, 0, 1, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       1, 2, 1, 1, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 0,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 0, 2, 2, 0, 2, 1, 2, 0, 2, 2, 2, 0, 2, 2, 0, 1, 2, 0, 2, 0, 2,
       2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 0, 0, 1, 2,
       1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 1, 0, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1,
       2, 2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 0,
       2, 2, 2, 1, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 1,

In [64]:
train['Embarked'] = train['Embarked'].fillna('S')

In [65]:
le.fit_transform(train['Embarked'])

array([2, 0, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2,
       1, 2, 2, 2, 0, 2, 1, 2, 0, 0, 1, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       1, 2, 1, 1, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 0,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 0, 2, 2, 0, 2, 1, 2, 0, 2, 2, 2, 0, 2, 2, 0, 1, 2, 0, 2, 0, 2,
       2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 0, 0, 1, 2,
       1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 1, 0, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1,
       2, 2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 0,
       2, 2, 2, 1, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 1,

# (4) 원 핫 인코딩(One Hot Encoding)

In [69]:
train = pd.read_csv("C:/Users/YHJ/Desktop/Data 교육/수업자료/MachineLearning/titanic_train.csv")
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [67]:
train['Embarked'].value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

In [68]:
train['Embarked']=train['Embarked'].fillna('S')
train['Embarked'].value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

In [70]:
train['Embarked_num']=LabelEncoder().fit_transform(train['Embarked'])
train['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

Embarked는 탑승 항구의 이니셜을 나타냄

그리고 우리는 LabelEncdoer를 통해 수치형으로 변환해줌

하지만 이대로 데이터를 기계학습ML 시키면 기계는 데이터 안에서 관계를 학습함.
(즉, 'S'=2, 'Q'=1이라고 되어있는데, Q + Q=S 가 된다고 학습함.)

그렇기 때문에 독립적인 데이터는 별도로 column으로 분리하고, 각각의 컬럼에 해당하는 값에만 True, 나머지는 False를 가짐
**=> 원핫인코딩**

In [71]:
train['Embarked'][:6]

0    S
1    C
2    S
3    S
4    S
5    Q
Name: Embarked, dtype: object

In [72]:
train['Embarked_num'][:6]

0    2
1    0
2    2
3    2
4    2
5    1
Name: Embarked_num, dtype: int32

In [73]:
pd.get_dummies(train['Embarked_num'][:6])

0  1  2
0  0  0  1
1  1  0  0
2  0  0  1
3  0  0  1
4  0  0  1
5  0  1  0

In [75]:
one_hot = pd.get_dummies(train['Embarked_num'][:6])
one_hot.columns = ['C','Q','S']

one_hot

C  Q  S
0  0  0  1
1  1  0  0
2  0  0  1
3  0  0  1
4  0  0  1
5  0  1  0

위와 같이 column을 분리시켜 **카테고리형->수치형**으로 변환하면서 생기는
수치형 값의 관계를 끊어주어 독립적인 형태로 바꾸어줌

**원핫인코딩** : 카테고리(계절, 항구, 성별, 종류 등)의 특성을 가지는 column에 적용

# (5) 전처리 : 정규화(Normalize)
    
column간에 다른 min, max값을 가지는 경우, 정규화를 통해 최소치/최대치값의 척도를 맞춰줌

ex)
- 네이버 영화평점 (0~10점) : [2, 4, 6, 8, 10]
- 넷플릭스 영화평점 (0~5점) : [1, 2, 3, 4, 5]

In [81]:
movie = {'naver':[2, 4, 6, 8, 10],
        'netflix':[1, 2, 3, 4, 5]}

In [82]:
movie = pd.DataFrame(data=movie)
movie

naver  netflix
0      2        1
1      4        2
2      6        3
3      8        4
4     10        5

In [85]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
min_max_movie = min_max_scaler.fit_transform(movie)
pd.DataFrame(min_max_movie, columns=['naver','netflix'])

naver  netflix
0   0.00     0.00
1   0.25     0.25
2   0.50     0.50
3   0.75     0.75
4   1.00     1.00

# (6) 표준화(Standard Scaling)
- **평균 = 0, 표준편차 =1** 이 되도록 변환

In [86]:
from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()

In [87]:
# 샘플 데이터 생성
x = np.arange(10) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# x배열의 인덱스9 값에 1000할당 [0, 1, 2, 3, 4, 5, 6, 7, 8, 1000]
x[9]= 1000 

In [88]:
x.mean(), x.std()

(103.6, 298.8100399919654)

In [95]:
scaled = standard_scaler.fit_transform(x.reshape(-1,1))

# StandardScaler는 2차원 배열 필요

In [91]:
x.mean(), x.std()

(103.6, 298.8100399919654)

In [92]:
scaled.mean(), scaled.std()

(4.4408920985006264e-17, 1.0)

In [96]:
round(scaled.mean(), 2) , scaled.std()
#부동소수점 연산 오차로 0이 아닌 값이 나올수 있기 때문에 round 필요 

(0.0, 1.0)