### 행/열 삭제 : drop
- df.drop('행이름',0)
    - 행 삭제 후 df로 결과를 반환
- df.drop('행이름',1)
    - 열 삭제 후 df로 결과를 반환
- inplace=True : 원본반영

In [45]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

import numpy as np
import pandas as pd
import seaborn as sns

In [20]:
df2=pd.DataFrame(np.random.randint(10,size=(4,8)))
df2['total']=df2[[0,1,2,3,4,5,6,7]].sum(axis=1)
df2.loc['max_data']=df2[[0,1,2,3,4,5,6,7]].max(axis=0)
df2

0    1    2    3    4    5    6    7  total
0         6.0  2.0  2.0  3.0  8.0  3.0  9.0  6.0   39.0
1         4.0  0.0  9.0  0.0  5.0  7.0  9.0  0.0   34.0
2         9.0  8.0  3.0  6.0  0.0  9.0  5.0  0.0   40.0
3         1.0  6.0  9.0  4.0  9.0  2.0  9.0  0.0   40.0
max_data  9.0  8.0  9.0  6.0  9.0  9.0  9.0  6.0    NaN

In [21]:
# total 열 삭제
df2.drop('total',1,inplace=True)
df2
df2.drop('max_data',0)
df2

C:\Users\YHJ\AppData\Local\Temp\ipykernel_15936\2354260271.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df2.drop('total',1,inplace=True)


0    1    2    3    4    5    6    7
0         6.0  2.0  2.0  3.0  8.0  3.0  9.0  6.0
1         4.0  0.0  9.0  0.0  5.0  7.0  9.0  0.0
2         9.0  8.0  3.0  6.0  0.0  9.0  5.0  0.0
3         1.0  6.0  9.0  4.0  9.0  2.0  9.0  0.0
max_data  9.0  8.0  9.0  6.0  9.0  9.0  9.0  6.0

C:\Users\YHJ\AppData\Local\Temp\ipykernel_15936\2354260271.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df2.drop('max_data',0)


0    1    2    3    4    5    6    7
0  6.0  2.0  2.0  3.0  8.0  3.0  9.0  6.0
1  4.0  0.0  9.0  0.0  5.0  7.0  9.0  0.0
2  9.0  8.0  3.0  6.0  0.0  9.0  5.0  0.0
3  1.0  6.0  9.0  4.0  9.0  2.0  9.0  0.0

0    1    2    3    4    5    6    7
0         6.0  2.0  2.0  3.0  8.0  3.0  9.0  6.0
1         4.0  0.0  9.0  0.0  5.0  7.0  9.0  0.0
2         9.0  8.0  3.0  6.0  0.0  9.0  5.0  0.0
3         1.0  6.0  9.0  4.0  9.0  2.0  9.0  0.0
max_data  9.0  8.0  9.0  6.0  9.0  9.0  9.0  6.0

### NaN값 처리 함수 
- df.dropna(axis=0/1)
    - NaN값이 있는 열 또는 행을 삭제
    - 원본에반영되지 않음
- df.fillna(0)
    - NaN 값을 정해진 숫자로 채움
    - 원본 반영되지 않음

In [22]:
df2

0    1    2    3    4    5    6    7
0         6.0  2.0  2.0  3.0  8.0  3.0  9.0  6.0
1         4.0  0.0  9.0  0.0  5.0  7.0  9.0  0.0
2         9.0  8.0  3.0  6.0  0.0  9.0  5.0  0.0
3         1.0  6.0  9.0  4.0  9.0  2.0  9.0  0.0
max_data  9.0  8.0  9.0  6.0  9.0  9.0  9.0  6.0

In [23]:
# 결측치 값 적용 - NaN값 생성(np.nan 속성)
df2.iloc[0,0] = np.nan
df2

0    1    2    3    4    5    6    7
0         NaN  2.0  2.0  3.0  8.0  3.0  9.0  6.0
1         4.0  0.0  9.0  0.0  5.0  7.0  9.0  0.0
2         9.0  8.0  3.0  6.0  0.0  9.0  5.0  0.0
3         1.0  6.0  9.0  4.0  9.0  2.0  9.0  0.0
max_data  9.0  8.0  9.0  6.0  9.0  9.0  9.0  6.0

In [24]:
# NaN이 포함된 행을 삭제 
df2.dropna(axis=0)

0    1    2    3    4    5    6    7
1         4.0  0.0  9.0  0.0  5.0  7.0  9.0  0.0
2         9.0  8.0  3.0  6.0  0.0  9.0  5.0  0.0
3         1.0  6.0  9.0  4.0  9.0  2.0  9.0  0.0
max_data  9.0  8.0  9.0  6.0  9.0  9.0  9.0  6.0

In [25]:
# NaN이 포함된 열을 삭제 
df2.dropna(axis=1,inplace=True) #원본에 반영
df2.iloc[0,0]=np.nan
df2

1    2    3    4    5    6    7
0         NaN  2.0  3.0  8.0  3.0  9.0  6.0
1         0.0  9.0  0.0  5.0  7.0  9.0  0.0
2         8.0  3.0  6.0  0.0  9.0  5.0  0.0
3         6.0  9.0  4.0  9.0  2.0  9.0  0.0
max_data  8.0  9.0  6.0  9.0  9.0  9.0  6.0

In [34]:
# NaN값을 특정 값으로 대체

df2.fillna(1, inplace=True) #원본반영

1    2    3    4    5    6    7
0         1.0  2.0  3.0  8.0  3.0  9.0  6.0
1         0.0  9.0  0.0  5.0  7.0  9.0  0.0
2         8.0  3.0  6.0  0.0  9.0  5.0  0.0
3         6.0  9.0  4.0  9.0  2.0  9.0  0.0
max_data  8.0  9.0  6.0  9.0  9.0  9.0  6.0

1    2    3    4    5    6    7
0         1.0  2.0  3.0  8.0  3.0  9.0  6.0
1         0.0  9.0  0.0  5.0  7.0  9.0  0.0
2         8.0  3.0  6.0  0.0  9.0  5.0  0.0
3         6.0  9.0  4.0  9.0  2.0  9.0  0.0
max_data  8.0  9.0  6.0  9.0  9.0  9.0  6.0

### 데이터프레임의 형변환
- df.astype(자료형)
- 전체 데이터에 대해 형변환을 진행

In [36]:
df2.iloc[0,0]=np.nan
df2

1    2    3    4    5    6    7
0         NaN  2.0  3.0  8.0  3.0  9.0  6.0
1         0.0  9.0  0.0  5.0  7.0  9.0  0.0
2         8.0  3.0  6.0  0.0  9.0  5.0  0.0
3         6.0  9.0  4.0  9.0  2.0  9.0  0.0
max_data  8.0  9.0  6.0  9.0  9.0  9.0  6.0

In [38]:
# 결측치를 0으로 채우면서 df의 데이터를 정수형으로 변환
df2.fillna(0)[1].astype(int)

0           0
1           0
2           8
3           6
max_data    8
Name: 1, dtype: int32

### 열 또는 행에 동일한 연산 반복 적용 : apply()
- apply()함수는 df의 행이나 열에 복잡한 연산을 vectorizing할 수 있게 해줌
- 동일한 연산(함수화 되어있어야 함)을 모든 열혹은 모든 행에 반복적용 할 때 사용
- apply(반복적용할함수, axis=0/1)
    + 0 : 열마다 반복
    + 1 : 행마다 반복

In [40]:
# 예제 df 생성
df3 = pd.DataFrame({
    'a':[1,3,4,3,4],
    'b':[2,3,1,4,5],
    'c':[1,5,2,4,4]})
df3

a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  4  4
4  4  5  4

In [41]:
# np.sum() : 전달된 첫번재 인수 데이터들의 합산 결과를 반환 
np.sum([1,2,3])

6

In [44]:
np.sum(df3['a'])
np.sum(df3['b'])
np.sum(df3['c'])

for i in ['a','b','c']:
    print(np.sum(df3[i]))
    
df3.apply(np.sum,0)

15

15

16

15
15
16


a    15
b    15
c    16
dtype: int64

In [46]:
titanic=pd.read_csv("C:/Users/YHJ/Desktop/data/test.csv")
del titanic['Unnamed: 0']
titanic.tail(2)

titanic.to_csv("C:/Users/YHJ/Desktop/data/test.csv") 

survived  pclass   sex   age  sibsp  parch   fare embarked  class  who  \
889         1       1  male  26.0      0      0  30.00        C  First  man   
890         0       3  male  32.0      0      0   7.75        Q  Third  man   

     adult_male deck embark_town alive  alone  
889        True    C   Cherbourg   yes   True  
890        True  NaN  Queenstown    no   True

In [47]:
#titanic df의 alive, sex, class열에 대해서 value_counts() 함수를 적용
titanic[['alive','sex','class']].apply(pd.value_counts,0)

alive    sex  class
First     NaN    NaN  216.0
Second    NaN    NaN  184.0
Third     NaN    NaN  491.0
female    NaN  314.0    NaN
male      NaN  577.0    NaN
no      549.0    NaN    NaN
yes     342.0    NaN    NaN

### 사용자 정의 함수를 apply()에 사용하는 예제

- 사용자 정의 함수 생성
- 사용자로부터 시리즈를 전달받아(매게변수) 해당시리즈의 최대값과 최소값 차이를 구해 반환
- diff를 정의


In [51]:
def diff(x): #x는 시리즈
    return x.max()-x.min()

df3

a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  4  4
4  4  5  4

In [52]:
# 함수 호출
diff(df3['a'])
diff(df3['b'])
diff(df3['c'])

3

4

4

In [53]:
# apply함수 적용
df3.apply(diff,0)

a    3
b    4
c    4
dtype: int64

In [54]:
pd.Series(3)
pd.Series(3).max()

0    3
dtype: int64

3

### 1회성 함수 lambda함수를 apply()에 사용하는 예제

In [55]:
(lambda x : x.max()-x.min())(df3['a'])

3

In [56]:
# 각열에 대해 최대값과 최소값의 차이를 구하기
df3.apply(lambda x : x.max()-x.min(),0)

# 혹은
df3.max(axis=0)-df3.min(axis=0)

a    3
b    4
c    4
dtype: int64

In [59]:
# apply()로  df의 행이나 열에 적용되어지는 함수가 행/열자체가 아닌 요소에 적용되는 함수라면 각 요소마다 함수를 적용시켜줌.

# np.square 함수는 행/열 별 각 원소에 대해 제곱승 연산을 진행함으로 행적용이나 열적용 모두 동일한 결과가 나타남
np.square([1,2,3])
df3
df3.apply(np.square,0)
df3.apply(np.square,1)

array([1, 4, 9], dtype=int32)

a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  4  4
4  4  5  4

a   b   c
0   1   4   1
1   9   9  25
2  16   1   4
3   9  16  16
4  16  25  16

a   b   c
0   1   4   1
1   9   9  25
2  16   1   4
3   9  16  16
4  16  25  16

### 데이터 값을 카테고리 값으로 변환
 - 값의 크기를 기준으로 하여 카테고리 값으로 변환하고 싶을 때

    1. cut(data,bins,labels)
        - data : 구간 나눌 실제 값
        - bins : 구간 경계 값
        - labes : 카테고리 값
    2. qcut(data,구간수,labels)
        - 똑같이 나눔

In [66]:
# 구간을 나눌 실제 값 : 관측데이터
ages=[0,0,5,4,6,4,5,2,10,21,23,37,15,38,31,61,20,41,31,100]

data = ages
bins = [0,4,18,25,35,60,100]
labels=['영유아','미성년자','청년','중년','장년','노년']

# 구간 최소값 < 구간 <= 구간최대값
# 0~4구간 : 영유아 0살 < 영유아 <=4
# labels의 순서는 bins의 순서와 동일해야 함 

In [67]:
len(data)
cats = pd.cut(data,bins,labels=labels)
cats

20

[NaN, NaN, '미성년자', '영유아', '미성년자', ..., '노년', '청년', '장년', '중년', '노년']
Length: 20
Categories (6, object): ['영유아' < '미성년자' < '청년' < '중년' < '장년' < '노년']

In [70]:
#리스트 형변환
cat_list = list(cats)
cat_list

[nan,
 nan,
 '미성년자',
 '영유아',
 '미성년자',
 '영유아',
 '미성년자',
 '영유아',
 '미성년자',
 '청년',
 '청년',
 '장년',
 '미성년자',
 '장년',
 '중년',
 '노년',
 '청년',
 '장년',
 '중년',
 '노년']

In [73]:
test = pd.DataFrame({'나이':ages,'연령대':cat_list})
test
test['연령대'].value_counts()

나이   연령대
0     0   NaN
1     0   NaN
2     5  미성년자
3     4   영유아
4     6  미성년자
5     4   영유아
6     5  미성년자
7     2   영유아
8    10  미성년자
9    21    청년
10   23    청년
11   37    장년
12   15  미성년자
13   38    장년
14   31    중년
15   61    노년
16   20    청년
17   41    장년
18   31    중년
19  100    노년

미성년자    5
영유아     3
청년      3
장년      3
중년      2
노년      2
Name: 연령대, dtype: int64

### Categorical 클랙스 객체
- 카테고리명 속성 : Categorical.categories
    - 카테고리명 저장
- 코드 속성 : Categorical.codes
    - 인코딩한 카테고리 값을 정수로 가짐

In [77]:
type(cats)

cats.categories #cats 변수 내의 범주 index를 저장 

cats.codes

pandas.core.arrays.categorical.Categorical

Index(['영유아', '미성년자', '청년', '중년', '장년', '노년'], dtype='object')

array([-1, -1,  1,  0,  1,  0,  1,  0,  1,  2,  2,  4,  1,  4,  3,  5,  2,
        4,  3,  5], dtype=int8)

### 구간 경계선을 지정하지 않고 데이터 개수가 같도록 지정한 수의 구간으로 분할 : qcut()
- 형식 : pd.qcut(data, 구간수, labels=[d1,d2, ...])
- 예) 1000개의 데이터를 4구간으로 나눈다면?
    - qcut 명령어를 사용한 구간마다 250개씩 나누게 됨
    - 단, 같은 숫자인 경우에는 같은 구간으로 처리함 

In [78]:
# 랜덤정수 20개를 생성하고 생성된 정수를 4개 구간으로 나누기
# 각 구간의 label은 Q1, Q2, Q3, Q4로 설정
# 랜덤정수 생성 : 범위 0-19, size-20
# seed 설정해서 재 실행해도 랜덤정수가 변하지 않도록 생성

np.random.seed(2)
data = np.random.randint(20,size=20)
data

array([ 8, 15, 13,  8, 11, 18, 11,  8,  7,  2, 17, 11, 15,  5,  7,  3,  6,
        4, 10, 11])

In [80]:
qcat = pd.qcut(data,4,labels=['Q1','Q2','Q3','Q4'])
qcat

['Q2', 'Q4', 'Q4', 'Q2', 'Q3', ..., 'Q1', 'Q1', 'Q1', 'Q3', 'Q3']
Length: 20
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [81]:
np.sort(data)

array([ 2,  3,  4,  5,  6,  7,  7,  8,  8,  8, 10, 11, 11, 11, 11, 13, 15,
       15, 17, 18])

In [82]:
pd.value_counts(qcat)

Q1    5
Q2    5
Q3    5
Q4    5
dtype: int64

In [87]:
df0=pd.DataFrame(data, columns=["관측수"])

df0['범주']=qcat
df0

관측수  범주
0     8  Q2
1    15  Q4
2    13  Q4
3     8  Q2
4    11  Q3
5    18  Q4
6    11  Q3
7     8  Q2
8     7  Q2
9     2  Q1
10   17  Q4
11   11  Q3
12   15  Q4
13    5  Q1
14    7  Q2
15    3  Q1
16    6  Q1
17    4  Q1
18   10  Q3
19   11  Q3

### 인덱스 설정 함수
- set_index(), reset_index() 데이터 프레임 인덱스 설정

1. set_index() : 기존 행 인덱스를 제거하고 데이터 열 중 하나를 인덱스로 설정
2. reset_index() : 기존 행 인덱스를 제거하고 기본 인덱스로 변경
    - 기본 인덱스 : 0부터 1씩 증가하는 정수 인덱스 

In [91]:
# 예제 데이터프레임 생성
df3 = pd.DataFrame({
    'a':[1,3,4,3,4],
    'b':[2,3,1,4,5],
    'c':[1,5,2,4,4]
})
df3

a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  4  4
4  4  5  4

In [98]:
# df3의 'a'열을 인덱스로 설정
df3.set_index('a')
df3.set_index('a',inplace=True) # 원본 반영

b  c
a      
1  2  1
3  3  5
4  1  2
3  4  4
4  5  4

In [101]:
# 인덱스값이 관측값이 아니거나 불필요한 경우 df의 열데이터로 추가되지 않게해야 함
# drop=True (기존 인덱스 삭제)
df3.reset_index(drop=True, inplace=True)
df3

b  c
0  2  1
1  3  5
2  1  2
3  4  4
4  5  4

### index 이름 변경
- rename(index={현재 index:바꿀index}) : 행인덱스
- rename(columns={현재 index:바꿀index}) : 열인덱스

In [102]:
# 행인덱스 값 변경
df3.rename(index={0:'1반',1:'2반'})

b  c
1반  2  1
2반  3  5
2   1  2
3   4  4
4   5  4

In [103]:
df3.rename(columns={'b':'학생'})

학생  c
0   2  1
1   3  5
2   1  2
3   4  4
4   5  4

### 리스트 내포 연산
* 리스트 내포 for문의 일반 문법
    - [표현식(연산식) for항목 in반복가능객체 if조건문]
    - if조건문은 생략 가능 
    - 반복가능객체 : 리스트, 튜플, 딕셔너리, range()등

In [104]:
### 리스트 내포 for문
a = [1,2,3,4]

In [105]:
#위 리스트에 각 원소에 2배 원소값을 만들고 리스트로 저장(반복문 사용)

a=[1,2,3,4]
result=[]

for num in a :
    result.append(num*2)
    
result

[2, 4, 6, 8]

In [106]:
result = [num*2 for num in a] 
result

[2, 4, 6, 8]

In [108]:
#내포 for문을 이용해 생성후 리스트로 추가하기 (반복문 이용)
test =[]
for i in range(1,5):
    test.append('id'+str(i))
test

['id1', 'id2', 'id3', 'id4']